start with experimental lua reverse proxy, just for fun

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -2,7 +2,7 @@
 # Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.53)
-AC_INIT(xauxi, 0.0.1, ia97lies@users.sourceforge.net)
+AC_INIT(httest, 0.0.1, ia97lies@sourceforge.net)
 AC_CONFIG_AUX_DIR([config])
 AM_CONFIG_HEADER([config/config.h])
 
@@ -14,13 +14,12 @@ m4_ifdef([AM_INIT_AUTOMAKE], [AM_INIT_AUTOMAKE]) dnl 2.57
 # Setting up C compiler stuff 
 AC_PROG_CC
 AC_PROG_CPP
-AC_PROG_CXX
 AC_AIX
 AC_ISC_POSIX
-AC_MINIX
 AC_HEADER_STDC
 AC_CHECK_HEADERS([unistd.h])
 AC_PROG_LIBTOOL
+AC_CONFIG_MACRO_DIR([m4])
 
 # Checks for typedefs, structures, and compiler characteristics.
 dnl 2.53 also doesn't have this
@@ -33,22 +32,65 @@ AC_FUNC_MALLOC
 AC_FUNC_SELECT_ARGTYPES
 AC_CHECK_FUNCS([bzero select socket])
 
-AC_ARG_ENABLE([use-static], AS_HELP_STRING(--enable-use-static, use archive libs not shared libraries))
-AC_ARG_WITH(bullet-includes,AS_HELP_STRING(--with-bullet-includes=PATH,path to bullet include files),
-	[if test ! -d $withval; then AC_MSG_ERROR($withval is not a directory); else BULLET_INCLUDE_PATH="${withval}"; fi],
-	[BULLET_INCLUDE_PATH=""])
-AC_ARG_WITH(bullet-libs,AS_HELP_STRING(--with-bullet-libs=PATH,path to bullet libraries),
-	[if test ! -d $withval; then AC_MSG_ERROR($withval is not a directory); else BULLET_LIB_PATH="${withval}"; fi],
-	[BULLET_LIB_PATH=""])
+# customize settings
+AC_ARG_ENABLE([use-static], AS_HELP_STRING(--enable-use-static,Try to use archives instead of shared libraries))
+AC_ARG_ENABLE([full-static], AS_HELP_STRING(--enable-full-static,Try to compile a statical linked executable))
+AC_ARG_WITH(apr,AS_HELP_STRING(--with-apr=PATH,path to apr-1-config script),
+	[if test ! -x $withval/apr-1-config; then AC_MSG_ERROR($withval/apr-1-config do not exist or is not executable); else APR_CONFIG="$withval/apr-1-config"; fi],
+	[APR_CONFIG="apr-1-config"])
+AC_ARG_WITH(apr-util,AS_HELP_STRING(--with-apr-util=PATH,path to apu-1-config script),
+	[if test ! -x $withval/apu-1-config; then AC_MSG_ERROR($withval/apu-1-config do not exist or is not executable); else APU_CONFIG="$withval/apu-1-config"; fi],
+	[APU_CONFIG="apu-1-config"])
+AC_ARG_WITH(apr-iconv,AS_HELP_STRING(--with-apr-iconv=PATH,path to apr-iconv directory),
+	[if test ! -f $withval/include/apr_iconv.h; then 
+	   AC_MSG_ERROR($withval/include/apr_iconv.h do not exist); 
+	 else 
+	   APR_ICONV_INCLUDES="-I$withval/include"; 
+	   APR_ICONV_LIBS="-L$withval/lib/.libs"; 
+	 fi],
+	[APR_ICONV_INCLUDES="";
+	 APR_ICONV_LIBS=""])
+AC_ARG_WITH(pcre,AS_HELP_STRING(--with-pcre=PATH,path to pcre-config script),
+	[if test ! -x $withval/pcre-config; then AC_MSG_ERROR($withval/pcre-config do not exist or is not executable); else PCRE_CONFIG="$withval/pcre-config"; fi],
+	[PCRE_CONFIG="pcre-config"])
+AC_ARG_WITH(lua,AS_HELP_STRING(--with-lua=PATH,path to lua source dir),
+	[if test ! -d $withval; then AC_MSG_ERROR($withval is not a directory); else LUA_LIB_PATH="-L${withval}"; LUA_INCLUDES="-I${withval}"; LUA_LIB="-llua"; fi],
+        [LUA_LIB_PATH=""; if test -d /usr/include/lua5.1; then LUA_INCLUDES="-I/usr/include/lua5.1"; else LUA_INCLUDES=""; fi; if test -f /usr/lib/liblua5.1.a -o -f /usr/lib/liblua5.1.so; then LUA_LIB="-llua5.1"; else LUA_LIB="-llua"; fi])
+AC_ARG_WITH(ssl,AS_HELP_STRING(--with-ssl=PATH,path to openssl source),
+	[if test ! -d $withval; then AC_MSG_ERROR($withval is not a directory); else OPENSSL_LIB_PATH="-L${withval}"; OPENSSL_INCLUDES="-I${withval}/include"; fi],
+	[OPENSSL_LIB_PATH=""; OPENSSL_INCLUDES=""])
 
-if test "$enable_use_static" = "yes"; then
-  BULLET_LIB="$BULLET_LIB_PATH/libBulletDynamics.a $BULLET_LIB_PATH/libBulletCollision.a $BULLET_LIB_PATH/libBulletSoftBody.a $BULLET_LIB_PATH/libLinearMath.a"
-else
-  BULLET_LIB="-L$BULLET_LIB_PATH -lBulletDynamics -lBulletCollision -lBulletSoftBody -lLinearMath"
+APR_VERSION=`$APR_CONFIG --version`
+if test ! "$?" = "0"; then
+  echo "libapr is missing"
+  exit -1
+fi
+APU_VERSION=`$APU_CONFIG --version`
+if test ! "$?" = "0"; then
+  echo "libaprutil is missing"
+  exit -1
+fi
+PCRE_VERSION=`$PCRE_CONFIG --version`
+if test ! "$?" = "0"; then
+  echo "libpcre is missing"
+  exit -1
 fi
 
-CPPFLAGS="-I$BULLET_INCLUDE_PATH"
-LIBS="$BULLET_LIB -lGL -lGLU -lglut -lnsl"
+# Store settings for includes, libs and flags
+INCLUDES="`$APR_CONFIG --includes` `$APU_CONFIG --includes` $OPENSSL_INCLUDES $APR_ICONV_CONFIG"
+CFLAGS="`$APR_CONFIG --cflags` `$PCRE_CONFIG --cflags` $CFLAGS $INCLUDES"
+CPPFLAGS="`$APR_CONFIG --cppflags` $CPPFLAGS"
+LIBS="$OPENSSL_LIB_PATH -lssl -lcrypto `$APR_CONFIG --link-ld`  `$APU_CONFIG --link-ld` `$APR_CONFIG --libs` `$APU_CONFIG --libs` `$PCRE_CONFIG --libs` -lz -lm"
+
+# if link static
+if test "$enable_full_static" = "yes"; then
+  LDFLAGS="-all-static $LDFLAGS"
+fi
+
+# if link static
+if test "$enable_use_static" = "yes"; then
+  LDFLAGS="-static $LDFLAGS"
+fi
 
 # generate makefiles
 AC_CONFIG_FILES([Makefile
